package igor.project.entities;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "Types")
public class Type {

    @Id
    @GeneratedValue // Id generated by hibernate
    @Column(name = "Type_id", unique = true, nullable = false, precision = 5)
    private long id;

    @Column(name = "Type_name", unique = true, nullable = false, precision = 5)
    private String name;

//    @OneToMany(mappedBy = "type")
//    private List<Capacity> capacities = new ArrayList<Capacity>();

    public Type() {
    }

    // Only type name; id should be generated
    //public Type(long id, String name) {
    public Type(String name) {
     //   this.id = id;
        this.name = name;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
